from django.contrib import admin
from django.contrib.auth import views as auth
from django.urls import path
from workspace import companion_views, diagnostic_views, views, connection_views, device_views, firmware_views, deployment_views, console_views, core_views

urlpatterns = [
    path('', views.landing, name='landing'),
    path('health/', views.health, name='health'),
    path('accounts/login/', views.SignInView.as_view(), name='login'),
    path('accounts/logout/', auth.LogoutView.as_view(), name='logout'),
    path('accounts/password/', auth.PasswordChangeView.as_view(template_name='registration/password.html', success_url='/accounts/password/done/'), name='password_change'),
    path('accounts/password/done/', auth.PasswordChangeDoneView.as_view(template_name='registration/password_done.html'), name='password_change_done'),
    path('home/', views.page, name='home'),
    path('devices/', device_views.devices, name='devices'),
    path('devices/add/', device_views.onboarding, name='onboarding'),
    path('devices/diagnostics/c6/', diagnostic_views.c6_probe, name='c6_probe'),
    path('devices/firmware/release/', firmware_views.release, name='firmware_release'),
    path('devices/firmware/review-bundle/', firmware_views.review_bundle, name='firmware_review_bundle'),
    path('devices/firmware/artifacts/<str:digest>.bin', firmware_views.artifact, name='firmware_artifact'),
    path('devices/interface-preview/', device_views.interface_preview, name='interface_preview'),
    path('devices/<uuid:pk>/', device_views.detail, name='device_detail'),
    path('devices/<uuid:pk>/console/', console_views.console, name='device_console'),
    path('devices/<uuid:pk>/companion/', companion_views.companion, name='device_companion'),
    path('devices/<uuid:pk>/core/', core_views.core, name='device_core'),
    path('devices/<uuid:pk>/core/commands/', core_views.command, name='device_core_command'),
    path('apps/packages/<str:package_id>/revoke/', core_views.revoke_package, name='app_package_revoke'),
    path('devices/<uuid:pk>/console/session/', console_views.start, name='device_console_start'),
    path('devices/<uuid:pk>/console/session/<uuid:session_id>/', console_views.state, name='device_console_state'),
    path('devices/<uuid:pk>/console/session/<uuid:session_id>/commands/', console_views.command, name='device_console_command'),
    path('devices/<uuid:pk>/console/session/<uuid:session_id>/stop/', console_views.stop, name='device_console_stop'),
    path('devices/<uuid:pk>/revoke/', device_views.revoke, name='device_revoke'),
    path('devices/<uuid:pk>/updates/', deployment_views.updates, name='device_updates'),
    path('devices/<uuid:pk>/updates/reconcile-usb/', deployment_views.reconcile_local, name='device_update_reconcile_usb'),
    path('devices/<uuid:pk>/updates/<uuid:job_id>/progress/', deployment_views.progress, name='device_update_progress'),
    path('devices/<uuid:pk>/updates/<uuid:job_id>/recovery.bin', deployment_views.recovery_artifact, name='device_update_recovery_artifact'),
    path('devices/<uuid:pk>/updates/<uuid:job_id>/cancel/', deployment_views.cancel, name='device_update_cancel'),
    path('api/devices/v1/<uuid:pk>/firmware/identity/', deployment_views.identity),
    path('api/devices/v1/<uuid:pk>/updates/poll/', deployment_views.poll),
    path('api/devices/v1/<uuid:pk>/updates/<uuid:job_id>/report/', deployment_views.report),
    path('api/devices/v1/<uuid:pk>/updates/<uuid:job_id>/status/', deployment_views.status),
    path('api/devices/v1/<uuid:pk>/updates/<uuid:job_id>/artifact/', deployment_views.artifact),
    path('api/devices/v1/enroll/', device_views.enrollment_start),
    path('api/devices/v1/enroll/<uuid:pk>/exchange/', device_views.enrollment_exchange),
    path('api/devices/v1/<uuid:pk>/heartbeat/', device_views.heartbeat),
    path('api/devices/v1/<uuid:pk>/companion/session/', companion_views.device_ticket),
    path('api/devices/v1/<uuid:pk>/console/sync/', console_views.sync),
    path('api/devices/v1/<uuid:pk>/diagnostics/events/', core_views.diagnostic_upload),
    path('api/devices/v1/<uuid:pk>/apps/sync/', core_views.app_sync),
    path('api/devices/v1/<uuid:pk>/apps/<str:package_id>/package/', core_views.app_package),
    path('api/devices/v1/<uuid:pk>/core/commands/<uuid:command_id>/ack/', core_views.command_ack),
    path('apps/', views.page, {'section': 'apps'}, name='apps'),
    path('connections/', connection_views.connections, name='connections'),
    path('connections/<uuid:pk>/replace/', connection_views.replace_key, name='replace_key'),
    path('connections/<uuid:pk>/delete/', connection_views.delete_connection, name='delete_connection'),
    path('connections/<uuid:pk>/voice/', connection_views.voice_preview, name='voice_preview'),
    path('connections/<uuid:pk>/ticket/', connection_views.audio_ticket, name='audio_ticket'),
    path('settings/', views.settings, name='settings'),
    path('admin/', admin.site.urls),
]
