# Generated by Django 5.2.17 on 2026-09-13 02:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_companion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('gemini', 'Gemini Live'), ('openai', 'OpenAI Realtime')], max_length=16)),
                ('label', models.CharField(max_length=80)),
                ('encrypted_key', models.TextField(editable=False)),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('validation', models.CharField(default='untested', editable=False, max_length=16)),
                ('checked_at', models.DateTimeField(editable=False, null=True)),
                ('result_code', models.CharField(blank=True, editable=False, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('provider', models.CharField(max_length=16)),
                ('mode', models.CharField(max_length=8)),
                ('status', models.CharField(default='starting', max_length=16)),
                ('result_code', models.CharField(blank=True, max_length=40)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.providerconnection')),
            ],
        ),
        migrations.CreateModel(
            name='AudioGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('revision', models.PositiveIntegerField()),
                ('browser_session', models.CharField(max_length=40)),
                ('mode', models.CharField(choices=[('check', 'check'), ('voice', 'voice')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.providerconnection')),
            ],
        ),
    ]
