# Generated by Django 5.2.17 on 2026-09-13 02:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_providerconnection_audiosession_audiogrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRateBucket',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('hardware_profile', models.CharField(max_length=80)),
                ('credential_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(editable=False, null=True)),
                ('last_seen', models.DateTimeField(editable=False, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=80)),
                ('chip_revision', models.CharField(blank=True, max_length=20)),
                ('transport', models.CharField(blank=True, max_length=16)),
                ('config_version', models.PositiveIntegerField(default=1)),
                ('acknowledged_version', models.PositiveIntegerField(default=0)),
                ('volume', models.PositiveSmallIntegerField(default=40)),
                ('microphone_muted', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('proof_hash', models.CharField(max_length=64)),
                ('hardware_profile', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('device', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.device')),
            ],
        ),
    ]
