# Generated by Django 5.2.17 on 2026-09-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_deviceratebucket_device_deviceenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hardware_report',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='device',
            name='hardware_reported_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
