# Generated by Django 5.2.17 on 2026-09-13 07:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_device_hardware_report_device_hardware_reported_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareRelease',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=64)),
                ('channel', models.CharField(max_length=32)),
                ('sequence', models.PositiveIntegerField()),
                ('policy', models.JSONField()),
                ('directory', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'channel', 'sequence'), name='firmware_release_sequence_unique')],
            },
        ),
        migrations.CreateModel(
            name='FirmwareDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_app_sha256', models.CharField(max_length=64)),
                ('idempotency_key', models.UUIDField()),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('verifying', 'Verifying'), ('rebooting', 'Rebooting'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('rolled_back', 'Rolled back'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('report_sequence', models.PositiveIntegerField(default=0)),
                ('bytes_written', models.PositiveIntegerField(default=0)),
                ('last_report', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=32)),
                ('needs_attention', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmware_deployments', to='workspace.device')),
                ('previous_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workspace.firmwarerelease')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.firmwarerelease')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceFirmware',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='firmware_state', serialize=False, to='workspace.device')),
                ('app_sha256', models.CharField(max_length=64)),
                ('confirmed_sequence', models.PositiveIntegerField()),
                ('confirmed_at', models.DateTimeField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.firmwarerelease')),
            ],
        ),
        migrations.CreateModel(
            name='FirmwareDeploymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('report', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workspace.firmwaredeployment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('deployment', 'sequence'), name='firmware_event_sequence_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='firmwaredeployment',
            constraint=models.UniqueConstraint(fields=('device', 'idempotency_key'), name='firmware_request_idempotent'),
        ),
        migrations.AddConstraint(
            model_name='firmwaredeployment',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['queued', 'downloading', 'verifying', 'rebooting'])), fields=('device',), name='one_active_firmware_deployment'),
        ),
    ]
