# Generated by Django 5.2.17 on 2026-09-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_native_companion'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicefirmware',
            name='last_poll_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
