# Generated by Django 5.2.17 on 2026-09-15 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_devicefirmware_last_poll_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPackage',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('policy', models.JSONField()),
                ('envelope', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCoreStatus',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='core_status', serialize=False, to='workspace.device')),
                ('core_version', models.CharField(max_length=31)),
                ('api_version', models.PositiveSmallIntegerField()),
                ('app_id', models.CharField(blank=True, max_length=64)),
                ('app_version', models.CharField(blank=True, max_length=31)),
                ('heap_free_bytes', models.PositiveIntegerField()),
                ('stack_min_bytes', models.PositiveIntegerField()),
                ('reported_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAppAssignment',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='app_assignment', serialize=False, to='workspace.device')),
                ('disabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workspace.apppackage')),
                ('previous_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workspace.apppackage')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAdminCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField()),
                ('kind', models.CharField(max_length=20)),
                ('state', models.CharField(default='queued', max_length=12)),
                ('result_code', models.CharField(blank=True, max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_commands', to='workspace.device')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workspace.apppackage')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('device', 'idempotency_key'), name='admin_command_idempotent')],
            },
        ),
        migrations.CreateModel(
            name='DeviceDiagnosticEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boot_id', models.CharField(max_length=16)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(max_length=20)),
                ('operation', models.CharField(max_length=24)),
                ('error_code', models.CharField(blank=True, max_length=32)),
                ('reset_reason', models.CharField(blank=True, max_length=24)),
                ('core_version', models.CharField(blank=True, max_length=31)),
                ('app_version', models.CharField(blank=True, max_length=31)),
                ('heap_free_bytes', models.PositiveIntegerField(null=True)),
                ('stack_min_bytes', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_events', to='workspace.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('device', 'boot_id', 'sequence'), name='diagnostic_boot_event_unique')],
            },
        ),
    ]
