# Generated by Django 5.2.17 on 2026-09-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0010_apppackage_devicecorestatus_deviceappassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicediagnosticevent',
            name='audio_stack_min_bytes',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='devicediagnosticevent',
            name='dma_free_bytes',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='devicediagnosticevent',
            name='dma_largest_bytes',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
