# Generated by Django 5.2.17 on 2026-09-15 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0011_devicediagnosticevent_audio_stack_min_bytes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceImageObservation',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='image_observation', serialize=False, to='workspace.device')),
                ('app_sha256', models.CharField(max_length=64)),
                ('firmware_version', models.CharField(max_length=31)),
                ('observed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceFirmwareRecoveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_app_sha256', models.CharField(max_length=64)),
                ('new_app_sha256', models.CharField(max_length=64)),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_events', to='workspace.device')),
                ('new_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workspace.firmwarerelease')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('previous_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workspace.firmwarerelease')),
            ],
        ),
    ]
